#########################
# Featured publications #
#########################

- id: doi:10.1182/blood.2024027270
  _title: Single-cell panleukemia signatures of HSPC-like blasts predict drug response and clinical outcome
  image: "images/publications/blood-2025.jpg"
  group: featured


- id: doi:10.1038/s43018-024-00863-5
  _title: A multiomic atlas identifies a treatment-resistant, bone marrow progenitor-like cell population in T cell acute lymphoblastic leukemia 
  image: "images/publications/NatureCancer-2024.jpg"
  group: featured

- id: doi:10.1182/blood.2021013442
  _title: Single-cell multiomics reveals increased plasticity, resistant populations, and stem-cell–like blasts in KMT2A-rearranged leukemia
  image: "images/publications/blood-2022.jpg"
  group: featured

- id: doi:10.1158/2159-8290.CD-20-1677
  _title: Integrative Bulk and Single-Cell Profiling of Premanufacture T-cell Populations Reveals Factors Mediating Long-Term Persistence of CAR T-cell Therapy
  image: "images/publications/CancerDiscovery-2021.jpg"
  group: featured

- id: doi:10.1016/j.celrep.2019.11.065
  _title: Spatial Genome Re-organization between Fetal and Adult Hematopoietic Stem Cells
  image: "images/publications/CellRep-2019.jpg"
  group: featured

- id: doi:10.1038/nmeth.3488
  _title: A microfluidic device for epigenomic profiling using 100 cells
  image: "images/publications/NatureMethods-2015.jpg"
  group: featured

